os: linux
language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-arm-none-eabi
    - build-essential
    - libc6-dev
    - libnewlib-arm-none-eabi
script:
- make